config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'
  get  "/auth/:provider/callback" => "sessions#create", as: "login"
  get '/auth/:provider', to: lambda{|env| [404, {}, ["Not Found"]]}, as: 'auth'
  get  "/signout" => "sessions#destroy", as: "signout"

  resources :categories, only: [:show] do
    resources :items, only: [:show]
  end

  get "/checkout", to: "carts#checkout", as: "checkout"
  get "/cart_info", to: "carts#info", as: "cart_info"
  get "/select_store", to: "carts#select_store", as: "select_store"
  post "/store_reply", to: "carts#info", as: "store_reply"
  post "/confirm_cart", to: "carts#confirm", as: "confirm_cart"
  get "/confirm_cart", to: "carts#confirm"
  post "/submit_order", to: "carts#submit", as: "submit_order"
  get "/success", to: "carts#success", as: "success"
  get "/password_resets/edit", to: "password_resets#edit"
  put "/password_resets/update", to: "password_resets#update"
  get "/password_resets/success", to: "password_resets#success"

  resources :cart_items, only: [:create, :destroy] do
    member do
      patch "update_quantity"
      patch "update_spec"
    end
  end

  resources :orders, only: [:index, :show]
  resources :favorite_items, only: [:index] do
    member do
      get :favorite
      get :remove
    end

  end
  # 助理後台
  namespace :staff do
    root "categories#index"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"

    resources :categories, only: [:show, :index]

    resources :items do
      resources :photos, except: [:show]

      resources :item_specs, except: [:show]
    end
  end

  resources :allpay, only:[] do
    collection do
      post "/create/:order_id", to: "allpay#create", as: "create"
      post "status_update"
      post "create_reply"
    end
  end

  # 管理員後台
  namespace :admin do
    root "categories#index"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"
    get "/checkout", to: "admin_carts#checkout", as: "checkout"
    post "/submit", to: "admin_carts#submit", as: "submit_order"

    resources :admin_cart_items, only: [:create, :destroy] do
      collection do
        post "add"
        post "get_by_id"
      end
      member do
        patch "update_quantity"
        patch "update_spec"
      end
    end

    resources :confirm_items, only: [:index] do
      # collection do
      #   get "/:taobao_supplier_id/confirmation", to: "confirm_items#confirmation", as: "confirmation"
      # end
    end

    resources :items do
      collection do
        get "search"
      end

      member do
        get "specs"
        patch "on_shelf"
        patch "off_shelf"
      end

      resources :photos, except: [:show]

      resources :item_specs, except: [:show] do
        member do
          patch "on_shelf"
          patch "off_shelf"
          get "style_pic"
        end
      end
    end

    resources :categories, only: [:new, :create, :show, :index, :edit, :update] do
      # 商品重新排序
      collection do
        post "sort_items_priority"
      end
    end

    resources :users, only: [:index, :show, :create, :update] do
      collection do
        # 外界POST request
        post "import_user", to: "users#import_user"
      end
    end

    get "users/show_uid/:uid", to: "users#show_uid", as: "uid_user"

    resources :counties, only: [:index, :show] do
      resources :towns, only: [:index, :show] do
        resources :roads, only: [:index, :show] do
          resources :stores, only: [:index, :show]
        end
      end
    end

    resources :orders, only: [:index, :show, :update] do
      collection do
        get "exporting_files"
        get "status_index"
        get "search"
      end

      member do
        patch "update_status"
        get "select_orders"
        post "combine_orders"
      end
    end

    # 註冊裝置
    resources :device_registrations, only: [:index, :show]

    # 推播訊息
    resources :notifications, only: [:index, :show, :new, :create] do
      collection do
        get :get_items
      end
    end

    # 銷售統計
    resources :sales_reports, only: [:index] do
      collection do
        get "item_sales_result"
        get "item_revenue_result"
        get "cost_statistics_index"
        post "/cost_statistics_index", to: "sales_reports#cost_statistics_create"
        get "sales_income_result"
      end
    end

    resources :taobao_suppliers, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        get "items"
      end
    end

    resources :mail_records, only: [] do
      collection do
        patch "/sending_survey_email/:order_id/", to: "mail_records#sending_survey_email", as: "sending_survey_email"
      end
    end

    resources :messages, only: [:index, :new, :create, :show, :destroy]
    resources :promotions, only: [:index, :new, :create, :destroy]
    resources :shop_infos, except: [:edit, :update]
  end

  # API for App
  get 'api/android_version' => 'api#android_version'
  namespace :api do
    namespace :v1 do
      # 分類API
      resources :categories, only: [:index, :show]

      # 商品API
      resources :items, only: [:index, :show] do
        member do
          # 商品樣式資料
          get "spec_info"
        end
      end

      # 用戶API
      resources :users, only: [:create, :show, :update]

      # 訂單API
      resources :orders, only: [:create, :show, :index] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
          get "by_email_phone"
        end
      end

      # 超商API
      resources :counties, only: [:index, :show] do
        resources :towns, only: [:index, :show] do
          resources :roads, only: [:index, :show] do
            resources :stores, only: [:index, :show]
          end
        end
      end

      # 註冊裝置
      resources :device_registrations, only: [:create]
    end

    namespace :v2 do
      # 訂單API
      resources :orders, only: [:show, :index] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
        end
      end
    end

    namespace :v3 do
      resources :counties, only: [:index] do
        resources :towns, only: [:index] do
          resources :roads, only: [:index] do
            resources :stores, only: [:index]
          end
        end
      end
      resources :users, only: [:create]
      resources :categories, only: [:index] do
        resources :items, only: [:index, :show]
      end
      resources :device_registrations, only: [:create]
      resources :orders, only: [:create, :show] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
          get "by_user_email"
          get "by_email_phone"
        end
      end
      resources :messages, only: [:index, :show]
      resources :mmw_registrations, only: [:create] do
        collection do
          post "login"
          post "forget"
        end
      end
      resources :oauth_sessions, only: [:create]
      resources :shop_infos, only: [:index]
    end
  end
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  item_id     :integer
#  image       :string(255)
#  deleted_at  :datetime
#  created_at  :datetime
#  updated_at  :datetime
#  photo_intro :string(255)
#

class Photo < ActiveRecord::Base
  # acts_as_paranoid
  
  belongs_to :item

  mount_uploader :image, ImageUploader
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < AdminController
  before_action :require_manager
  before_action :find_item
  before_action :find_photo, only: [:edit, :update, :destroy]

  def index
    @photos = @item.photos
  end

  def new
    @photo = @item.photos.new
  end

  def create
    # 多張圖片上傳
    begin
      create_photo_params[:images].each do |image|
        @item.photos.create!(image: image)
      end
      flash[:notice] = "圖片上傳完成"
      redirect_to admin_item_photos_path(@item)
    rescue Exception => e
      flash.now[:alert] = "請確認上傳圖片是否正確"
    end

    # 單張圖片上傳
    # @photo = @item.photos.new(photo_params)

    # if @photo.save!
    #   flash[:notice] = "新增圖片成功"
    #   redirect_to admin_item_photos_path(@item)
    # else
    #   flash.now[:alert] = "請確認上傳圖片是否正確"
    #   render :edit
    # end
  end

  def edit
  end

  def update
    if @photo.update!(update_photo_params)
      flash[:notice] = "編輯完成"
      redirect_to admin_item_photos_path(@item)
    else
      flash[:alert] = "請確認編輯內容是否正確"
      render :edit
    end
  end

  def destroy
    @photo.destroy!
    flash[:warning] = "圖片已刪除"
    redirect_to admin_item_photos_path(@item)
  end

  private

  def find_item
    @item = Item.includes(:photos).find(params[:item_id])
  end

  def find_photo
    @photo = @item.photos.find(params[:id])
  end

  def create_photo_params
    params.require(:photo).permit(:image, :photo_intro).merge!(images: params[:images])
  end

  def update_photo_params
    params.require(:photo).permit(:image, :photo_intro)
  end
end

app/controllers/staff/photos_controller.rb
class Staff::PhotosController < StaffController
  before_action :require_assistant
  before_action :find_item
  before_action :find_photo, only: [:edit, :update, :destroy]

  def index
    @photos = @item.photos
  end

  def new
    @photo = @item.photos.new
  end

  def create
    # 多張圖片上傳
    begin
      create_photo_params[:images].each do |image|
        @item.photos.create!(image: image)
      end
      flash[:notice] = "圖片上傳完成"
      redirect_to staff_item_photos_path(@item)
    rescue Exception => e
      flash.now[:alert] = "請確認上傳圖片是否正確"
    end

    # 單張圖片上傳
    # @photo = @item.photos.new(photo_params)

    # if @photo.save!
    #   flash[:notice] = "新增圖片成功"
    #   redirect_to admin_item_photos_path(@item)
    # else
    #   flash.now[:alert] = "請確認上傳圖片是否正確"
    #   render :edit
    # end
  end

  def edit
  end

  def update
    if @photo.update!(update_photo_params)
      flash[:notice] = "編輯完成"
      redirect_to staff_item_photos_path(@item)
    else
      flash[:alert] = "請確認編輯內容是否正確"
      render :edit
    end
  end

  def destroy
    @photo.destroy!
    flash[:warning] = "圖片已刪除"
    redirect_to staff_item_photos_path(@item)
  end

  private

  def find_item
    @item = Item.includes(:photos).find(params[:item_id])
  end

  def find_photo
    @photo = @item.photos.find(params[:id])
  end

  def create_photo_params
    params.require(:photo).permit(:image, :photo_intro).merge!(images: params[:images])
  end

  def update_photo_params
    params.require(:photo).permit(:image, :photo_intro)
  end
end

app/views/admin/photos/_edit_form.html.erb
<!-- Modal -->
<div class="modal fade" id="photo-<%= photo.id %>-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">編輯敘述</h4>
      </div>
      <%= form_for [:admin, @item, photo], html: { class: "form-horizontal" } do |f| %>
          <div class="form-group">            
            <%= f.label :photo_intro, "圖片描述", class: "col-sm-2 control-label" %>    
            <div class="col-sm-9">
              <%= f.text_area :photo_intro, { rows: 6, id: "item-photo-#{photo.id}", class: "form-control", placeholder: "請輸入描述" } %>        
            </div>
          </div>
        
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit "確認送出", class: "btn btn-primary" %>
            </div>
          </div>
        
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">關閉視窗</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/photos/_edit_form.html.haml
/ Modal
.modal.fade{"aria-labelledby" => "myModalLabel", :id => "photo-#{photo.id}-edit", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title 編輯敘述
      = form_for [:admin, @item, photo], html: { class: "form-horizontal" } do |f|
        .form-group
          = f.label :photo_intro, "圖片描述", class: "col-sm-2 control-label"
          .col-sm-9
            = f.text_area :photo_intro, { rows: 6, id: "item-photo-#{photo.id}", class: "form-control", placeholder: "請輸入描述" }
        .form-group
          .col-sm-offset-2.col-sm-10
            = f.submit "確認送出", class: "btn btn-primary"
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 關閉視窗

app/views/admin/photos/_form.html.erb
<!-- Modal -->
<div class="modal fade" id="photo-<%= photo.id %>-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">收件明細</h4>
      </div>
      <%= form_for [:admin, @item, photo], html: { id: "photo-#{photo.id}-edit", class: "form-horizontal" } do |f| %>
          <div class="form-group">            
            <%= f.label :photo_intro, "圖片描述", class: "col-sm-2 control-label" %>    
            <div class="col-sm-10">
              <%= f.cktext_area :photo_intro, rows: 6, class: "form-control", placeholder: "請輸入描述", :ckeditor => {:language => 'zh-TW'} %>        
            </div>
          </div>
        
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit "確認送出", class: "btn btn-primary" %>
              <%= link_to "取消離開", admin_item_photos_path(@item), class: "btn btn-warning" %>
            </div>
          </div>
        
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/photos/edit.html.erb
<div class="row">
  <div class="col-md-10">
    <div class="content-box-large">
      <div class="panel-heading">
        <div class="panel-title">
           編輯圖片<br>          
        </div>
        <div class="panel-options">
          <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
          <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
        </div>
      </div>

      <div class="panel-body">
        <!-- <div>
          <p class="">商品名稱： <%= @item.name %></p>
          <p class="">商品名稱： <%= image_tag(@photo.image.thumb.url) %></p>
        </div> -->
        
        <%= form_for [:admin, @item, @photo], html: { id: "photo-#{@photo.id}-edit", class: "form-horizontal" } do |f| %>
          <div class="form-inputs">
            <div class="form-group has-success has-feedback">            
              <%= f.label :photo_intro, "圖片描述", class: "col-sm-2 control-label" %>    
              <div class="col-sm-10">
                <%= f.cktext_area :photo_intro, rows: 6, class: "form-control", placeholder: "請輸入描述", :ckeditor => {:language => 'zh-TW'} %>        
              </div>
            </div>
          </div>
          <div class="actions">
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit "確認送出", class: "btn btn-primary" %>
                <%= link_to "取消離開", admin_item_photos_path(@item), class: "btn btn-warning" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/admin/photos/index.html.erb
<div class="panel-body">
  <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
    <div class="pull-right">
      <%= link_to "返回上頁", admin_item_path(@item), class: "btn btn-default btn-sm" %>
      <%= link_to "新增圖片", new_admin_item_photo_path, class: "btn btn-primary btn-sm" %>
    </div>
    <div class="breadcrumb-topbar">
      <ol class="breadcrumb">
        <li><a href="#">萌萌屋</a></li>
        <li><a href="<%= admin_item_path(@item) %>"><%= @item.name %></a></li>
        <li class="<%= "active" if current_page?(controller: "admin/photos") %>">
          圖片列表
        </li>
      </ol>
    </div>
    <thead>
      <tr>
        <th>圖片</th>
        <th>圖片敘述</th>
        <th>操作選項</th>
      </tr>
    </thead>
    <tbody>
      <% @photos.each do |photo| %>
        <tr>
          <td>
            <%= item_photo(photo, "thumb") %>
          </td>
          <td><%= raw photo.photo_intro %></td>
          <td>            
            <%= button_tag "編輯", data: { toggle: "modal", target: "#photo-#{photo.id}-edit" }, type: "button", class: "btn btn-default btn-xs" %>
            <%= render partial: "edit_form", locals: { photo: photo } %>
            <%= link_to "刪除", admin_item_photo_path(@item, photo), method: :delete, data: { confirm: "確定刪除?", disable_with: "刪除中..." }, class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/photos/index.html.haml
.panel-body
  %table#example.table.table-striped.table-bordered{:border => "0", :cellpadding => "0", :cellspacing => "0"}
    .pull-right
      = link_to "返回上頁", admin_item_path(@item), class: "btn btn-default btn-sm"
      = link_to "新增圖片", new_admin_item_photo_path, class: "btn btn-primary btn-sm"
    .breadcrumb-topbar
      %ol.breadcrumb
        %li
          %a{:href => "#"} 萌萌屋
        %li
          %a{:href => "#{admin_item_path(@item)}"}= @item.name
        %li{:class => "#{"active" if current_page?(controller: "admin/photos")}"}
          圖片列表
    %thead
      %tr
        %th 圖片
        %th 圖片敘述
        %th 操作選項
    %tbody
      - @photos.each do |photo|
        %tr
          %td
            = item_photo(photo, "thumb")
          %td= raw photo.photo_intro
          %td
            = button_tag "編輯", data: { toggle: "modal", target: "#photo-#{photo.id}-edit" }, type: "button", class: "btn btn-default btn-xs"
            = render partial: "edit_form", locals: { photo: photo }
            = link_to "刪除", admin_item_photo_path(@item, photo), method: :delete, data: { confirm: "確定刪除?", disable_with: "刪除中..." }, class: "btn btn-danger btn-xs"

app/views/admin/photos/new.html.erb
<div class="row">
  <div class="col-md-10">
    <div class="content-box-large">
      <div class="breadcrumb-topbar">
        <ol class="breadcrumb">
          <li><a href="#">萌萌屋</a></li>
          <li><a href="<%= admin_item_path(@item) %>"><%= @item.name %></a></li>          
          <li class="<%= "active" if current_page?(controller: "admin/photos") %>">
            新增圖片
          </li>
        </ol>
      </div>
      <div class="panel-heading">
        <div class="panel-title">
          新增圖片<br>
          <p class="center">商品名稱： <%= @item.name %></p>
        </div>
          <div class="panel-options">
            <a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
            <a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
          </div>
        </div>
      <div class="panel-body">
        <%= form_for [:admin, @item, @photo], html: { multipart: true, class: "form-horizontal" } do |f| %>
    
          <div class="form-group">
            <%= f.label "選擇圖片", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= file_field_tag "images[]", { multiple: true, class: "form-control" }%>
            </div>

            <!-- <%= f.label :image, "選擇圖片", class: "col-sm-2 control-label" %> -->
            <div class="col-sm-10">
              <!-- <%= f.file_field :image, multiple: true, class: "form-control" %> -->
            </div>
          </div>

          <div class="form-group">            
            <%= f.label :photo_intro, "圖片描述", class: "col-sm-2 control-label" %>    
            <div class="col-sm-10">
              <%= f.text_area :photo_intro, rows: 6, class: "form-control", placeholder: "請輸入描述" %>
            </div>
          </div>
                  
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit "確認送出", class: "btn btn-primary" %>
              <%= link_to "取消離開", admin_item_photos_path(@item), class: "btn btn-warning" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/photos/new.html.haml
.row
  .col-md-10
    .content-box-large
      .breadcrumb-topbar
        %ol.breadcrumb
          %li
            %a{:href => "#"} 萌萌屋
          %li
            %a{:href => "#{admin_item_path(@item)}"}= @item.name
          %li{:class => "#{"active" if current_page?(controller: "admin/photos")}"}
            新增圖片
      .panel-heading
        .panel-title
          新增圖片
          %br/
          %p.center
            商品名稱： #{@item.name}
        .panel-options
          %a{"data-rel" => "collapse", :href => "#"}
            %i.glyphicon.glyphicon-refresh
          %a{"data-rel" => "reload", :href => "#"}
            %i.glyphicon.glyphicon-cog
      .panel-body
        = form_for [:admin, @item, @photo], html: { multipart: true, class: "form-horizontal" } do |f|
          .form-group
            = f.label "選擇圖片", class: "col-sm-2 control-label"
            .col-sm-10
              = file_field_tag "images[]", { multiple: true, class: "form-control" }
            / <haml_loud> f.label :image, &quot;選擇圖片&quot;, class: &quot;col-sm-2 control-label&quot; </haml_loud>
            .col-sm-10
              / <haml_loud> f.file_field :image, multiple: true, class: &quot;form-control&quot; </haml_loud>
          .form-group
            = f.label :photo_intro, "圖片描述", class: "col-sm-2 control-label"
            .col-sm-10
              = f.text_area :photo_intro, rows: 6, class: "form-control", placeholder: "請輸入描述"
          .form-group
            .col-sm-offset-2.col-sm-10
              = f.submit "確認送出", class: "btn btn-primary"
              = link_to "取消離開", admin_item_photos_path(@item), class: "btn btn-warning"