config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'
  get  "/auth/:provider/callback" => "sessions#create", as: "login"
  get '/auth/:provider', to: lambda{|env| [404, {}, ["Not Found"]]}, as: 'auth'
  get  "/signout" => "sessions#destroy", as: "signout"

  resources :categories, only: [:show] do
    resources :items, only: [:show]
  end

  get "/checkout", to: "carts#checkout", as: "checkout"
  get "/cart_info", to: "carts#info", as: "cart_info"
  get "/select_store", to: "carts#select_store", as: "select_store"
  post "/store_reply", to: "carts#info", as: "store_reply"
  post "/confirm_cart", to: "carts#confirm", as: "confirm_cart"
  get "/confirm_cart", to: "carts#confirm"
  post "/submit_order", to: "carts#submit", as: "submit_order"
  get "/success", to: "carts#success", as: "success"
  get "/password_resets/edit", to: "password_resets#edit"
  put "/password_resets/update", to: "password_resets#update"
  get "/password_resets/success", to: "password_resets#success"

  resources :cart_items, only: [:create, :destroy] do
    member do
      patch "update_quantity"
      patch "update_spec"
    end
  end

  resources :orders, only: [:index, :show]
  resources :favorite_items, only: [:index] do
    member do
      get :favorite
      get :remove
    end

  end
  # 助理後台
  namespace :staff do
    root "categories#index"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"

    resources :categories, only: [:show, :index]

    resources :items do
      resources :photos, except: [:show]

      resources :item_specs, except: [:show]
    end
  end

  resources :allpay, only:[] do
    collection do
      post "/create/:order_id", to: "allpay#create", as: "create"
      post "status_update"
      post "create_reply"
    end
  end

  # 管理員後台
  namespace :admin do
    root "categories#index"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"
    get "/checkout", to: "admin_carts#checkout", as: "checkout"
    post "/submit", to: "admin_carts#submit", as: "submit_order"

    resources :admin_cart_items, only: [:create, :destroy] do
      collection do
        post "add"
        post "get_by_id"
      end
      member do
        patch "update_quantity"
        patch "update_spec"
      end
    end

    resources :confirm_items, only: [:index] do
      # collection do
      #   get "/:taobao_supplier_id/confirmation", to: "confirm_items#confirmation", as: "confirmation"
      # end
    end

    resources :items do
      collection do
        get "search"
      end

      member do
        get "specs"
        patch "on_shelf"
        patch "off_shelf"
      end

      resources :photos, except: [:show]

      resources :item_specs, except: [:show] do
        member do
          patch "on_shelf"
          patch "off_shelf"
          get "style_pic"
        end
      end
    end

    resources :categories, only: [:new, :create, :show, :index, :edit, :update] do
      # 商品重新排序
      collection do
        post "sort_items_priority"
      end
    end

    resources :users, only: [:index, :show, :create, :update] do
      collection do
        # 外界POST request
        post "import_user", to: "users#import_user"
      end
    end

    get "users/show_uid/:uid", to: "users#show_uid", as: "uid_user"

    resources :counties, only: [:index, :show] do
      resources :towns, only: [:index, :show] do
        resources :roads, only: [:index, :show] do
          resources :stores, only: [:index, :show]
        end
      end
    end

    resources :orders, only: [:index, :show, :update] do
      collection do
        get "exporting_files"
        get "status_index"
        get "search"
      end

      member do
        patch "update_status"
        get "select_orders"
        post "combine_orders"
      end
    end

    # 註冊裝置
    resources :device_registrations, only: [:index, :show]

    # 推播訊息
    resources :notifications, only: [:index, :show, :new, :create] do
      collection do
        get :get_items
      end
    end

    # 銷售統計
    resources :sales_reports, only: [:index] do
      collection do
        get "item_sales_result"
        get "item_revenue_result"
        get "cost_statistics_index"
        post "/cost_statistics_index", to: "sales_reports#cost_statistics_create"
        get "sales_income_result"
      end
    end

    resources :taobao_suppliers, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        get "items"
      end
    end

    resources :mail_records, only: [] do
      collection do
        patch "/sending_survey_email/:order_id/", to: "mail_records#sending_survey_email", as: "sending_survey_email"
      end
    end

    resources :messages, only: [:index, :new, :create, :show, :destroy]
    resources :promotions, only: [:index, :new, :create, :destroy]
    resources :shop_infos, except: [:edit, :update]
  end

  # API for App
  get 'api/android_version' => 'api#android_version'
  namespace :api do
    namespace :v1 do
      # 分類API
      resources :categories, only: [:index, :show]

      # 商品API
      resources :items, only: [:index, :show] do
        member do
          # 商品樣式資料
          get "spec_info"
        end
      end

      # 用戶API
      resources :users, only: [:create, :show, :update]

      # 訂單API
      resources :orders, only: [:create, :show, :index] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
          get "by_email_phone"
        end
      end

      # 超商API
      resources :counties, only: [:index, :show] do
        resources :towns, only: [:index, :show] do
          resources :roads, only: [:index, :show] do
            resources :stores, only: [:index, :show]
          end
        end
      end

      # 註冊裝置
      resources :device_registrations, only: [:create]
    end

    namespace :v2 do
      # 訂單API
      resources :orders, only: [:show, :index] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
        end
      end
    end

    namespace :v3 do
      resources :counties, only: [:index] do
        resources :towns, only: [:index] do
          resources :roads, only: [:index] do
            resources :stores, only: [:index]
          end
        end
      end
      resources :users, only: [:create]
      resources :categories, only: [:index] do
        resources :items, only: [:index, :show]
      end
      resources :device_registrations, only: [:create]
      resources :orders, only: [:create, :show] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
          get "by_user_email"
          get "by_email_phone"
        end
      end
      resources :messages, only: [:index, :show]
      resources :mmw_registrations, only: [:create] do
        collection do
          post "login"
          post "forget"
        end
      end
      resources :oauth_sessions, only: [:create]
      resources :shop_infos, only: [:index]
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :require_manager
  before_action :find_order, only: [:show, :update, :update_status]
  skip_before_filter  :verify_authenticity_token, only: [:allpay_create, :allpay_status]

  def index
    @orders = Order.includes(:user, info: :store, items: :item).recent.paginate(page: params[:page])
  end

  def status_index
    params[:status] ||= 0
    @orders = Order.includes(:user, info: :store, items: :item).status(params[:status]).recent.paginate(page: params[:page])    
  end

  def show
    @info = @order.info
    @items = @order.items
  end

  def update
    if @order.update(order_params)
      @result = "訂單變更完成"
    else
      @result = "訂單變更失敗"
    end

    respond_to do |format|
      format.js
    end
  end

  def update_status
    status_param = params['status'].to_i
    if @order.update_attributes(status: status_param)
      @message = "已將編號：#{@order.id} 訂單狀態設為#{@order.status}"
    else
      Rails.logger.error("error: #{@order.errors.messages}")
      flash[:alert] = "請仔細確認訂單的實際處理進度"
    end

    respond_to do |format|
      format.js
    end
  end

  def exporting_files
    @order_for_file_page = @orders_for_file = Order.includes(:user, :info).recent.paginate(:page => params[:page])

    respond_to do |format|
      format.html
      format.csv { send_data @orders_for_file.to_csv }
    end
  end

  def search
    @search_results = Order.includes(:user, info: :store, items: :item).search_by_phone_or_email(params[:ship_phone_data], params[:ship_email_data]).paginate(:page => params[:page])
  end

  def select_orders
    current_order = Order.find(params[:id])
    @combine_orders = Order.enable_to_conbime.includes(:user, :info).search_by_phone_or_email(current_order.ship_phone, current_order.ship_email)
  end

  def combine_orders
    target_orders = Order.where(id: params[:selected_order_ids])
    target_infos = target_orders.map(&:info)
    target_items = target_orders.map(&:items).flatten

    combined_items_price = target_orders.map(&:items_price).inject(:+)
    combined_ship_fee = combined_items_price > 490 ? 0 : 60
    combined_total = combined_items_price + combined_ship_fee

    errors = []
    ActiveRecord::Base.transaction do
      order = Order.new
      order.uid = target_orders[0].uid
      order.user_id = target_orders[0].user_id
      order.items_price = combined_items_price
      order.ship_fee = combined_ship_fee
      order.total = combined_total
      order.device_registration_id = target_orders[0].device_registration_id
      order.note = "訂單編號：#{target_orders.map(&:id).join('，')} 併單"
      errors << order.errors.messages unless order.save

      info = OrderInfo.new
      info.order_id = order.id
      info.ship_name = target_infos[0].ship_name
      info.ship_phone = target_infos[0].ship_phone
      info.ship_store_code = target_infos[0].ship_store_code
      info.ship_store_id = target_infos[0].ship_store_id
      info.ship_store_name = target_infos[0].ship_store_name
      info.ship_email = target_infos[0].ship_email
      errors << info.errors.messages unless info.save

      target_items.each do |product|
        item = order.items.new
        item.item_name = product.item.name
        item.source_item_id = product.source_item_id
        item.item_spec_id = product.item_spec_id
        item.item_style = product.item_spec.style
        item.item_quantity = product.item_quantity
        item.item_price = product.item.price
        item.save
        errors << item.errors.messages unless item.save
      end

      raise ActiveRecord::Rollback if errors.present?
    end

    if errors.present?
      Rails.logger.error("error: #{errors}")
      flash.now["danger"] = "請檢查各訂單的明細資料"
      render :select_orders
    else
      target_orders.each { |order| order.update_column(:status, Order.statuses["訂單取消"]) }
      flash[:notice] = "併單已完成"
      redirect_to status_index_admin_orders_path
    end
  end

  private

  def find_order
    @order = Order.includes(:user, :info, :items).find(params[:id])
  end

  def order_params
    params.require(:order).permit(:total, :note, info_attributes: [:ship_phone, :ship_email, :id])
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApiController
  def create
    ActiveRecord::Base.transaction do
      # 訂單 Order
      order = Order.new
      order.uid = params[:uid]
      order.user_id = User.find_by(uid: params[:uid]).id
      order.items_price = params[:items_price]
      order.ship_fee = params[:ship_fee]
      order.total = params[:total]
      # Save user_id to device_registrations table if params[:registration_id] present
      unless params[:registration_id].nil?
        device_of_order = DeviceRegistration.find_or_initialize_by(registration_id: params[:registration_id])
        device_of_order.user = order.user
        device_of_order.save!
        order.device_registration = device_of_order
      end
      order.save!

      # 收件資訊 OrderInfo
      info = OrderInfo.new
      info.order_id = order.id
      info.ship_name = params[:ship_name]
      info.ship_phone = params[:ship_phone]
      info.ship_store_code = params[:ship_store_code]
      info.ship_store_id = params[:ship_store_id]
      info.ship_store_name = params[:ship_store_name]
      info.ship_email = get_info_email(params[:ship_email],order.user)
      info.save!

      # 商品明細 OrderItem
      params[:products].each do |product|
        item = OrderItem.new
        item.order_id = order.id
        item.item_name = product[:name]
        item.source_item_id = Item.find_by(name: product[:name]).id
        item.item_spec = ItemSpec.where(item_id: item.source_item_id).find_by(style: product[:style])
        item.item_style = product[:style]
        item.item_quantity = product[:quantity]
        item.item_price = product[:price]        
        item.save!
      end
      
      OrderMailer.delay.notify_order_placed(order)
    end

    render json: "Succes：新增一筆訂單"
  end

  def show
    order = Order.includes(:user, :info, :items).find(params[:id])
    info = order.info
    items = order.items
    result_order = order.generate_result_order
    render json: result_order
  end

  def user_owned_orders
    user_orders = Order.includes(:user).where("uid = ?", params[:uid]).recent.page(params[:page]).per_page(20)
    render json: user_orders, only: [:id, :uid, :total, :created_on, :status, :user_id]
  end

  def by_email_phone
    user_orders = Order.joins(:info).where("ship_email = ? and ship_phone = ?", params[:email], params[:phone]).recent
    render json: user_orders, only: [:id, :uid, :total, :created_on, :status, :user_id]
  end

  private

  def get_info_email(email_param,user)
    (email_param.present?) ? email_param : user.email
  end
end

app/controllers/api/v2/orders_controller.rb
class Api::V2::OrdersController < ApiController
  # TODO 重構整理

  def show
    order = Order.includes(:user, :info, :items).find(params[:id])
    info = order.info
    items = order.items
    result_order = order.generate_result_order
    render json: result_order
  end

  def user_owned_orders
    user_orders = Order.includes(:user).where("uid = ?", params[:uid]).recent.page(params[:page]).per_page(20)
    # result_user_orders = []

    render json: user_orders, only: [:id, :uid, :total, :created_on, :status, :user_id]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout 'user'

  before_action  :load_categories, :require_user

  def index
    @orders = current_user.orders.recent
    set_meta_tags title: "我的訂單", noindex: true
  end

  def show
    @order = current_user.orders.find(params[:id])
    @items = @order.items.includes(:item_spec)
    @info = @order.info
    set_meta_tags title: "訂單內容", noindex: true
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def phone_number_looking(order)
    order.info.ship_phone
  end

  def link_to_update_order_status(status_text, order)
    link_to status_text, update_status_admin_order_path(order, status: Order.statuses[status_text]), { method: :patch, remote: true, disable_with: '狀態更新中' }
  end

  def li_status_link(status)
    content_tag(:li, '' , class: eq_to_status?(status)) do
      link_to Order.statuses.key(status) + ": #{Order.count_status(status)}", status_index_admin_orders_path(status: status)
    end
  end

  def eq_to_status?(status)
    params[:status].to_i == status ? 'active' : ''
  end

  def order_status(status_number)
    Order.statuses.key(status_number)
  end

  def logistics_status(order)
    if order.logistics_status_code
      Logistics_Status[order.logistics_status_code]
    else
      "尚未建立資料"
    end
  end

  def create_allpay_index_button(order)
    if order.logistics_status_code.nil?
      button_to "傳送至歐付寶", create_allpay_index_path(order), remote: true, class: "btn btn-primary"
    else
      content_tag(:span, '已傳送至歐付寶', class: "label label-default")
    end
  end

  def link_to_send_survey_email(order)
    if order.status == "完成取貨" && order.survey_mail
     content_tag(:span, "已寄出", class: "label label-default")
    elsif order.status == "完成取貨" && order.survey_mail.nil?
      link_to "寄出問卷調查", sending_survey_email_admin_mail_records_path(order), class: "btn btn-info", method: :patch, data: { confirm: "確定寄送Email給：#{order.ship_name}？" }
    else
      content_tag(:span, "未完成取貨", class: "label label-warning")
    end
  end

  def blacklist_warning(order)
    if order.is_blacklisted
      content_tag(:span, "問題訂單", class: "label label-danger")
    end
  end

  def check_orders_to_combine(order)
    if params[:id].to_i == order.id
      check_box_tag "selected_order_ids[]", order.id, checked: true
    else
      check_box_tag "selected_order_ids[]", order.id
    end
  end

  def link_to_combine_orders(order)
    if order.status == "訂單成立" || order.status == "處理中"
      link_to "合併其他訂單", select_orders_admin_order_path(order), class: "btn btn-default"
    end
  end
end

app/views/admin/orders/_edit_order.html.haml
%button.btn.btn-default.btn-sm{"data-target" => "#edit-order-#{order.id}", "data-toggle" => "modal", remote: true, :type => "button"}
  編輯訂單
.modal.fade{"aria-labelledby" => "myModalLabel", :id => "edit-order-#{order.id}", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      = form_for [:admin, order], method: :patch, :html => {"data-target": "#edit-order-#{order.id}"}, remote: true, class: "edit-order" do |f|
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title 訂單明細
        .modal-body
          %h4#myModalLabel.modal-title 收件明細
          %ul.list-group
            - if order.info
              %li.list-group-item
                收件人姓名： #{order.ship_name}
              %li.list-group-item
                聯絡電話： #{order.ship_phone}
              %li.list-group-item
                Email： #{order.ship_email}
              %li.list-group-item
                門市店號： #{order.ship_store_code}
              %li.list-group-item
                門市名稱： #{order.ship_store_name}
              %li.list-group-item
                門市地址： #{order.address}
          %br/
          .form-group
            .form-group
              = f.label :total, "總金額"
              = f.text_field :total, class: 'form-control'
            .form-group
              = f.label :note, "訂單備註"
              = f.text_area :note, class: 'form-control', rows: 5, place_horder: order.note
            .form-group
              = f.fields_for :info do |info_f|
                = info_f.label :ship_email, "Email"
                = info_f.email_field :ship_email, class: 'form-control'
                %br
                = info_f.label :ship_phone, "聯絡電話"
                = info_f.number_field :ship_phone, class: 'form-control'
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 取消
          %button.btn.btn-primary{type: "submit"}  送出變更

app/views/admin/orders/_info_and_items_list.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :id => "order-#{order.id}", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title 訂單明細
      .modal-body
        %h4#myModalLabel.modal-title 收件明細
        %ul.list-group
          - if order.info
            %li.list-group-item
              收件人姓名： #{order.ship_name}
            %li.list-group-item
              聯絡電話： #{order.ship_phone}
            %li.list-group-item
              Email： #{order.ship_email}
            %li.list-group-item
              門市店號： #{order.ship_store_code}
            %li.list-group-item
              門市名稱： #{order.ship_store_name}
            %li.list-group-item
              門市地址： #{order.address}
        %br/
        %h4#myModalLabel.modal-title 商品明細
        %table.table.table-bordered
          %thead
            %tr.active
              %th 商品名稱
              %th 商品樣式
              %th 購買數量
              %th 商品單價
          %tbody
            - if order.items
              - order.items.each do |item|
                %tr.success
                  %td
                    = link_to item.item_name, admin_item_path(item.item)
                  %td= item.item_style
                  %td= item.item_quantity
                  %td= item.item_price
        %table.table.table-bordered
          %tbody
            %tr
              %td.info 訂單總金額
              %td= order.total
        %h4#myModalLabel.modal-title 訂單備註
        .note
          = order.note
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/admin/orders/_order_table.html.erb
<div class="panel-body">
  <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
    <thead>      
      <tr>
        <th>編號</th>
        <th>訂購用戶</th>
        <th>總金額</th>
        <th>訂單狀態</th>
        <th>收件明細</th>
        <th>商品明細</th>
        <th>操作選項</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= link_to order.info_user_name, admin_user_path(order.user) %></td>
          <td><%= order.total %></td>
          <td>
            <%= link_to "新增訂單", "#",{ id: "order-#{order.id}-placed", class: "btn btn-default #{order.status == "order_placed" ? "btn-lg" : "btn-xs"}" } %>
            <%= link_to "已出貨", item_shipping_admin_order_path(order), { method: :patch, remote: true, id: "order-#{order.id}-shipping", class: "btn #{order.status == "item_shipping" ? "btn-primary btn-lg" : "btn-default btn-xs"}" } %>
            <%= link_to "完成取貨", item_shipped_admin_order_path(order), { method: :patch, remote: true, id: "order-#{order.id}-shipped", class: "btn #{order.status == "item_shipped" ? "btn-success btn-lg" : "btn-default btn-xs"}" } %>
            <%= link_to "訂單取消", order_cancelled_admin_order_path(order), { method: :patch, remote: true, id: "order-#{order.id}-cancel", class: "btn #{order.status == "order_cancelled" ? "btn-warning btn-lg" : "btn-default btn-xs"}" } %>
          </td>

          <!-- 收件明細 -->
          <td>
            <%= render partial: "info_list", locals: { order: order } %>
          </td>

          <!-- 商品明細 -->
          <td>
            <%= render partial: "items_list", locals: { order: order } %>
          </td>

          <td>
            <ul class="list-unstyled">
              <li><%= link_to "查看" %></li>
              <li><%= link_to "編輯" %></li>
              <li><%= link_to "刪除" %></li>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/_order_table.html.haml
%br/
.apple_pagination
  = will_paginate orders, :container => false
.panel-body
  %table.table.table-striped.table-bordered{:border => "0", :cellpadding => "0", :cellspacing => "0"}
    %thead
      %tr
        %th 編號
        %th 訂購日期與狀態
        %th 訂購用戶
        %th 訂購商品
        %th 總金額
        %th 訂單操作
    %tbody
      - orders.each do |order|
        %tr
          %td
            %button.btn.btn-default.btn-sm{"data-target" => "#order-#{order.id}", "data-toggle" => "modal", :type => "button"}
              = order.id
            = render(partial: "info_and_items_list", locals: { order: order })
            %br
            = render(partial: "edit_order", locals: { order: order })
            %br
            = create_allpay_index_button(order)
          %td
            = order.created_on
            %br
            .dropdown{id: "dropdown-#{order.id}"}
              %button.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                %span{id: "current-#{order.id}-status"}= order.status
                %span.caret
              %ul.dropdown-menu.list-group
                %li                  
                  = link_to_update_order_status("處理中", order)
                %li
                  = link_to_update_order_status("配送中", order)
                %li
                  = link_to_update_order_status("已到店", order)
                %li
                  = link_to_update_order_status("完成取貨", order)
                %li
                  = link_to_update_order_status("未取訂貨", order)
                %li
                  = link_to_update_order_status("訂單變更", order)
                %li
                  = link_to_update_order_status("訂單取消", order)
            %hr
            物流狀態：
            %br
            %span{id: "logistis-#{order.id}"}= logistics_status(order)
          %td
            = blacklist_warning(order)
            %br
            = link_to order.info_user_name, admin_user_path(order.user)
            %br
            - statuses_count = order.user_orders.status_count
            購買次數：#{order.user_orders.count}
            %br
            完成取貨：#{statuses_count[Order.statuses["完成取貨"]]}
            %br
            未取訂貨：#{statuses_count[Order.statuses["未取訂貨"]]}
            %br
            = render partial: "order_status_tooltip", locals:{ order: order, statuses_count: statuses_count }
          %td
            %table.table.table-bordered
              %thead
                %tr.active
                  %th 編號
                  %th 名稱
                  %th 樣式
                  %th 數量
                  %th 訂購
              %tbody
                - if order.items
                  - order.items.each do |item|
                    %tr.success
                      %td= item.item.id
                      %td
                        = link_to item.item_name, admin_item_path(item.item)
                      %td= item.item_style
                      %td= item.item_quantity
                      %td
                        = form_tag add_admin_admin_cart_items_path, remote: true do
                          = hidden_field_tag :item_id, item.item.id
                          = hidden_field_tag :item_spec_id, item.item_spec_id
                          = hidden_field_tag :item_quantity, item.item_quantity
                          = hidden_field_tag :taobao_supplier_id, item.item.taobao_supplier_id
                          = submit_tag '新增至購物車', class: "btn btn-primary "
            %table.table.table-bordered
              %tbody
                %tr.active
                  %th 備註
                %tr
                  %td= order.note
          %td= order.total
          %td
            = link_to_send_survey_email(order)
            %hr
            = link_to_combine_orders(order)
.apple_pagination
  = will_paginate orders, :container => false
%br/

app/views/admin/orders/_update.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :id => "order-#{order.id}", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title 訂單明細
      .modal-body
        %h4#myModalLabel.modal-title 收件明細
        %ul.list-group
          - if order.info
            %li.list-group-item
              收件人姓名： #{order.ship_name}
            %li.list-group-item
              聯絡電話： #{order.ship_phone}
            %li.list-group-item
              門市店號： #{order.ship_store_code}
            %li.list-group-item
              門市名稱： #{order.ship_store_name}
            %li.list-group-item
              門市地址： #{order.address}
        %br/
        %h4#myModalLabel.modal-title 商品明細
        %table.table.table-bordered
          %thead
            %tr.active
              %th 商品名稱
              %th 商品樣式
              %th 購買數量
              %th 商品單價
          %tbody
            - if order.items
              - order.items.each do |item|
                %tr.success
                  %td
                    = link_to item.item_name, admin_item_path(item.source_item_id)
                  %td= item.item_style
                  %td= item.item_quantity
                  %td= item.item_price
        %h4#myModalLabel.modal-title 訂單備註
        .note
          = order.note
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/admin/orders/index.html.haml
.row
  .col-md-12.panel-warning
    .content-box-header.panel-heading
      .panel-title 所有訂單列表
    .content-box-large.box-with-header
      = render "search_form"
      %hr
      = render "order_table", orders: @orders

app/views/admin/orders/item_shipped.js.erb
$("#order-<%= @order.id %>-shipping").removeClass().addClass("btn btn-default btn-xs")
$("#order-<%= @order.id %>-placed").addClass("btn-xs")
$("#order-<%= @order.id %>-shipped").removeClass().addClass("btn btn-success btn-lg")
$("#order-<%= @order.id %>-cancel").removeClass().addClass("btn btn-default btn-xs")
$(function(){
  new PNotify({title: '已將訂單設為完成取貨'});
});

app/views/admin/orders/update_status.js.haml
$("#current-#{@order.id}-status").html('#{@order.status}')
$(function(){
new PNotify({title: "#{j(@message)}"});
});