config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'
  get  "/auth/:provider/callback" => "sessions#create", as: "login"
  get '/auth/:provider', to: lambda{|env| [404, {}, ["Not Found"]]}, as: 'auth'
  get  "/signout" => "sessions#destroy", as: "signout"

  resources :categories, only: [:show] do
    resources :items, only: [:show]
  end

  get "/checkout", to: "carts#checkout", as: "checkout"
  get "/cart_info", to: "carts#info", as: "cart_info"
  get "/select_store", to: "carts#select_store", as: "select_store"
  post "/store_reply", to: "carts#info", as: "store_reply"
  post "/confirm_cart", to: "carts#confirm", as: "confirm_cart"
  get "/confirm_cart", to: "carts#confirm"
  post "/submit_order", to: "carts#submit", as: "submit_order"
  get "/success", to: "carts#success", as: "success"
  get "/password_resets/edit", to: "password_resets#edit"
  put "/password_resets/update", to: "password_resets#update"
  get "/password_resets/success", to: "password_resets#success"

  resources :cart_items, only: [:create, :destroy] do
    member do
      patch "update_quantity"
      patch "update_spec"
    end
  end

  resources :orders, only: [:index, :show]
  resources :favorite_items, only: [:index] do
    member do
      get :favorite
      get :remove
    end

  end
  # 助理後台
  namespace :staff do
    root "categories#index"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"

    resources :categories, only: [:show, :index]

    resources :items do
      resources :photos, except: [:show]

      resources :item_specs, except: [:show]
    end
  end

  resources :allpay, only:[] do
    collection do
      post "/create/:order_id", to: "allpay#create", as: "create"
      post "status_update"
      post "create_reply"
    end
  end

  # 管理員後台
  namespace :admin do
    root "categories#index"
    get "/signin", to: "sessions#new"
    post "/signin", to: "sessions#create"
    delete "/signout", to: "sessions#destroy"
    get "/checkout", to: "admin_carts#checkout", as: "checkout"
    post "/submit", to: "admin_carts#submit", as: "submit_order"

    resources :admin_cart_items, only: [:create, :destroy] do
      collection do
        post "add"
        post "get_by_id"
      end
      member do
        patch "update_quantity"
        patch "update_spec"
      end
    end

    resources :confirm_items, only: [:index] do
      # collection do
      #   get "/:taobao_supplier_id/confirmation", to: "confirm_items#confirmation", as: "confirmation"
      # end
    end

    resources :items do
      collection do
        get "search"
      end

      member do
        get "specs"
        patch "on_shelf"
        patch "off_shelf"
      end

      resources :photos, except: [:show]

      resources :item_specs, except: [:show] do
        member do
          patch "on_shelf"
          patch "off_shelf"
          get "style_pic"
        end
      end
    end

    resources :categories, only: [:new, :create, :show, :index, :edit, :update] do
      # 商品重新排序
      collection do
        post "sort_items_priority"
      end
    end

    resources :users, only: [:index, :show, :create, :update] do
      collection do
        # 外界POST request
        post "import_user", to: "users#import_user"
      end
    end

    get "users/show_uid/:uid", to: "users#show_uid", as: "uid_user"

    resources :counties, only: [:index, :show] do
      resources :towns, only: [:index, :show] do
        resources :roads, only: [:index, :show] do
          resources :stores, only: [:index, :show]
        end
      end
    end

    resources :orders, only: [:index, :show, :update] do
      collection do
        get "exporting_files"
        get "status_index"
        get "search"
      end

      member do
        patch "update_status"
        get "select_orders"
        post "combine_orders"
      end
    end

    # 註冊裝置
    resources :device_registrations, only: [:index, :show]

    # 推播訊息
    resources :notifications, only: [:index, :show, :new, :create] do
      collection do
        get :get_items
      end
    end

    # 銷售統計
    resources :sales_reports, only: [:index] do
      collection do
        get "item_sales_result"
        get "item_revenue_result"
        get "cost_statistics_index"
        post "/cost_statistics_index", to: "sales_reports#cost_statistics_create"
        get "sales_income_result"
      end
    end

    resources :taobao_suppliers, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        get "items"
      end
    end

    resources :mail_records, only: [] do
      collection do
        patch "/sending_survey_email/:order_id/", to: "mail_records#sending_survey_email", as: "sending_survey_email"
      end
    end

    resources :messages, only: [:index, :new, :create, :show, :destroy]
    resources :promotions, only: [:index, :new, :create, :destroy]
    resources :shop_infos, except: [:edit, :update]
  end

  # API for App
  get 'api/android_version' => 'api#android_version'
  namespace :api do
    namespace :v1 do
      # 分類API
      resources :categories, only: [:index, :show]

      # 商品API
      resources :items, only: [:index, :show] do
        member do
          # 商品樣式資料
          get "spec_info"
        end
      end

      # 用戶API
      resources :users, only: [:create, :show, :update]

      # 訂單API
      resources :orders, only: [:create, :show, :index] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
          get "by_email_phone"
        end
      end

      # 超商API
      resources :counties, only: [:index, :show] do
        resources :towns, only: [:index, :show] do
          resources :roads, only: [:index, :show] do
            resources :stores, only: [:index, :show]
          end
        end
      end

      # 註冊裝置
      resources :device_registrations, only: [:create]
    end

    namespace :v2 do
      # 訂單API
      resources :orders, only: [:show, :index] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
        end
      end
    end

    namespace :v3 do
      resources :counties, only: [:index] do
        resources :towns, only: [:index] do
          resources :roads, only: [:index] do
            resources :stores, only: [:index]
          end
        end
      end
      resources :users, only: [:create]
      resources :categories, only: [:index] do
        resources :items, only: [:index, :show]
      end
      resources :device_registrations, only: [:create]
      resources :orders, only: [:create, :show] do
        collection do
          get "/user_owned_orders/:uid" => "orders#user_owned_orders"
          get "by_user_email"
          get "by_email_phone"
        end
      end
      resources :messages, only: [:index, :show]
      resources :mmw_registrations, only: [:create] do
        collection do
          post "login"
          post "forget"
        end
      end
      resources :oauth_sessions, only: [:create]
      resources :shop_infos, only: [:index]
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :cart_items, dependent: :destroy
  has_one :cart_info, dependent: :destroy
  belongs_to :user

  STEP = { checkout: 1, info: 2, confirm: 3}
  FREE_SHIPPING_PRICE = 490
  SHIP_FEE = 60


end

app/controllers/carts_controller.rb
require "uri"

class CartsController < ApplicationController
  layout 'cart'
  skip_before_action :verify_authenticity_token, only: :info
  before_action  :load_categories

  def checkout
    @step = Cart::STEP[:checkout]
    @items = current_cart.cart_items.includes({item: :specs}, :item_spec)
    if @items.empty?
      flash[:notice] = " 您的購物車目前是空的，快點加入您喜愛的商品吧！"
      redirect_to root_path
    end
    @total = total(@items)
    set_meta_tags title: "確認訂單", noindex: true
  end

  def info
    @step = Cart::STEP[:info]
    if params['CVSStoreID']
      @store = Store.find_by(store_code: params['CVSStoreID'])
    end
    set_meta_tags title: "訂購資料", noindex: true
  end

  def select_store
    cookies[:name] = params[:name]
    cookies[:email] = params[:email]
    cookies[:phone] = params[:phone]

    url = generate_url(ENV['ALL_PAY_URL'],
                       MerchantID: ENV['MERCHANT_ID'],
                       MerchantTradeNo: '1111',
                       LogisticsType: 'CVS',
                       LogisticsSubType: 'UNIMART',
                       IsCollection: 'Y',
                       ServerReplyURL: store_reply_url)

    render json: {url: url}
  end

  def confirm
    @step = Cart::STEP[:confirm]
    @info = {ship_name: params[:ship_name],
             ship_phone: params[:ship_phone],
             ship_email: params[:ship_email]}
    @store = Store.find(params[:store_id])
    @items = current_cart.cart_items.includes(:item, :item_spec)
    @total = total(@items)
    set_meta_tags title: "確認訂單", noindex: true
  end

  def submit
    items = current_cart.cart_items.includes(:item, :item_spec)
    store = Store.find(params[:store])
    order = create_order(items, params[:info], store)
    session[:cart_id] = nil
    OrderMailer.delay.notify_order_placed(order)

    redirect_to success_path
  end

  private

  def generate_url(url, params = {})
    uri = URI(url)
    uri.query = params.to_query
    uri.to_s
  end

  def create_order(cart_items, cart_info, store)
    order = Order.new
    order.uid = current_cart.user.uid
    order.user_id = current_cart.user_id
    order.items_price = total(cart_items)
    order.ship_fee = ship_fee(cart_items)
    order.total = total(cart_items)+ ship_fee(cart_items)
    order.save

    info = OrderInfo.new
    info.order_id = order.id
    info.ship_name = cart_info[:ship_name]
    info.ship_phone = cart_info[:ship_phone]
    info.ship_store_code = store.store_code
    info.ship_store_id = store.id
    info.ship_store_name = store.name
    info.ship_email = cart_info[:ship_email]
    info.save

    cart_items.each do |cart_item|
      item = OrderItem.new
      item.order_id = order.id
      item.item_name = cart_item.item.name
      item.source_item_id = cart_item.item_id
      item.item_spec_id = cart_item.item_spec_id
      item.item_style = cart_item.item_spec.style
      item.item_quantity = cart_item.item_quantity
      item.item_price = cart_item.item.special_price ||  cart_item.item.price
      item.save
    end

    order
  end
end

app/helpers/cart_helper.rb
module CartHelper
  def render_cart_step(step)
    content_tag(:div, @step > step ? "✓" : step , class: @step < step ? 'undone' : 'done')
  end

  def render_step_bar(step)
    content_tag(:div, '',  class: @step > step ?  'bar -full' : 'bar')
  end
end

app/views/carts/checkout.html.haml
= render 'partials/cart_steps', step: @step
.cart-show
  .icon-header.-pencil 訂單明細
  - if @cart.cart_items.any?
    .cart-result
      .header.row.visible-lg-block
        .col-lg-1 刪除訂單
        .col-lg-2 產品照片
        .col-lg-3 產品名稱
        .col-lg-2 產品樣式
        .col-lg-1 產品單價
        .col-lg-2 產品數量
        .col-lg-1 小計
      .divider.visible-lg-block
      - @items.each do |item|
        .item-bar.row{id: "cart-item-#{item.id}"}
          .col-lg-1.col-xs-1.cancel-block
            .cancel{"aria-label": "Close", 'data-toggle': "modal", 'data-target': "#modal-#{item.id}"}
            .modal.fade{"aria-labelledby" => "mySmallModalLabel", :role => "dialog", :tabindex => "-1", id: "modal-#{item.id}"}
              .modal-dialog
                .modal-content
                  .modal-body
                    %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} &times;
                    您確定要刪除此產品？
                  .modal-footer
                    %button.btn.btn-close{"data-dismiss": "modal", type: "button"} 關閉視窗
                    %button.btn.btn-confirm.cart-item-delete{type: "button", "data-dismiss": "modal", 'data-id': item.id,
                      'data-cart-id': @cart.id, onClick: analytic_event("checkout_step_1", "click", "product_delete")} 刪除
          .col-lg-2.col-xs-3.icon= image_tag(item.item_spec.style_pic.url, id: "item-spec-pic-#{item.id}")
          .col-lg-3.col-xs-8.itemname= item.item.name
          .col-lg-2.col-xs-7.select= select_tag "item_spec_id",options_from_collection_for_select(item.item.specs, 'id', 'style', item.item_spec_id ),   class: 'spec-select', id: 'select-specs', 'data-cart-item': item.id, 'data-cart-id': @cart.id
          .col-lg-1.col-xs-2.unitprice= item_current_price(item.item)
          .col-lg-2.col-sm-4.col-xs-3.quantity-box
            .quantity-minus{ 'data-id': item.id, onClick: analytic_event("checkout_step_1", "click", "number_change") } -
            = number_field_tag "cart-item-#{item.id}-quantity", item.item_quantity, class: 'quantity', min: 1, max: 99
            .quantity-plus{ 'data-id': item.id, onClick: analytic_event("checkout_step_1", "click", "number_change") } +
          .col-lg-1.col-sm-2.col-xs-3.subtotal{id: "cart-item-#{item.id}-subtotal"}= price_with_unit(item.subtotal)
      .divider
      .totalrow.row
        .col-lg-2.col-lg-offset-9.col-sm-5.col-xs-8.text
          %div 產品總額
          %div 運費（711超商取貨付款）
        .col-lg-1.col-lg-offset-0.col-sm-2.col-sm-offset-5.col-xs-4.number
          #cart-sum= price_with_unit(@total)
          #ship-fee= price_with_unit(ship_fee)
      .divider
      .totalrow.row
        .col-lg-2.col-lg-offset-9.col-sm-5.col-xs-8.text
          %div 總計
        .col-lg-1.col-lg-offset-0.col-sm-2.col-sm-offset-5.col-xs-4.number
          #totalprice= price_with_unit(@total + ship_fee)
    .submit-session
      - if current_user
        = link_to '下一步', cart_info_path , class: 'btn', onClick: analytic_event("checkout_step_2", "enter", "無")
      -else
        = link_to '', auth_path("facebook"), class: 'btn fb-login', onClick: analytic_event("checkout_step_1", "click", "facebook_login")
        = link_to '免註冊匿名購買', cart_info_path , class: 'btn', onClick: analytic_event("checkout_step_1", "click", "anonymous_purchase")

app/views/carts/confirm.html.haml
= render 'partials/cart_steps', step: @step
.cart-confirm
  .icon-header.-pencil 訂單明細
  .cart-result
    .header.row.visible-lg-block
      .col-lg-2 產品照片
      .col-lg-4 產品名稱
      .col-lg-2 產品樣式
      .col-lg-1 產品單價
      .col-lg-2 產品數量
      .col-lg-1 小計
    .divider.visible-lg-block
    - @items.each do |item|
      .item-bar.row{id: "cart-item-#{item.id}"}
        .col-lg-2.col-sm-2.col-xs-3.icon= image_tag(item.item.cover.icon.url)
        .col-lg-4.col-xs-8.itemname= item.item.name
        .col-lg-2.col-sm-10.col-xs-9.spec= item.item_spec.style
        .col-lg-1.col-sm-4.col-xs-2.price= item_current_price(item.item)
        .col-lg-2.col-sm-2.col-xs-2.quantity
          %div= item.item_quantity
        .col-lg-1.col-lg-offset-0.col-sm-2.col-sm-offset-1.col-xs-5.subtotal= price_with_unit(item.subtotal)
    .divider
    .totalrow.row
      .col-lg-2.col-lg-offset-9.col-xs-8.text
        %div 產品總額
        %div 運費（711超商取貨付款）
      .col-lg-1.col-xs-4.number
        #cart-sum= price_with_unit(@total)
        %div=  price_with_unit(ship_fee)
    .divider
    .totalrow.row
      .col-lg-2.col-lg-offset-9.col-xs-8.text
        %div 總計
      .col-lg-1.col-xs-4.number
        #totalprice= price_with_unit(@total + ship_fee)
.row
  .col-lg-6
    .icon-header.-pencil 訂購人資料
    .input-block.-info
      .group
        %div= "姓名：#{@info[:ship_name]}"
        %div= "電話：#{@info[:ship_phone]}"
        %div= "連絡信箱：#{@info[:ship_email]}"
  .col-lg-6
    .icon-header.-pencil 取貨門市資訊
    .input-block.-store
      .group
        = hidden_field_tag :store_id, '' ,value: @store.id
        %div= "門市名稱： #{@store.name}"
        %div= "地址： #{@store.address}"
= form_tag submit_order_path(info: @info, store: @store), method: :post do
  .submit-session
    =link_to '上一步', cart_info_path , class: 'btn btn-previous', onClick: analytic_event("checkout_step_3", "click", "previous_step")
    =submit_tag '送出訂單', class: 'btn', onClick: analytic_event("checkout_step_3", "click", "send_order")

app/views/carts/info.html.haml
= render 'partials/cart_steps', step: @step
.cart-info
  = form_tag confirm_cart_path, method: :post do
    .icon-header.-pencil 訂購人資料
    .input-block
      .group
        = label :ship_name, '姓名'
        = text_field_tag :ship_name, '' ,required: true, value: cookies[:name]
      .group
        = label :ship_phone, '電話'
        = text_field_tag :ship_phone, '' ,required: true, value: cookies[:phone]
      .group
        = label :ship_email, '電子信箱'
        = text_field_tag :ship_email, '' ,required: true, value: cookies[:email]
        .text *名稱和電話必需正確才能取貨
    .icon-header.-mark 7-11取貨門市資訊
    .input-block.-store
      .group
        %span 選擇7-11寄送門市
        =link_to '選擇門市', '',  class: 'btn regular-btn select-store', remote: true
      .divider
      .group
        = hidden_field_tag :store_id, '' ,value: @store ? @store.id : nil, required: true
        %div= @store ?  "門市名稱： #{@store.name}" : '請選擇送達門市'
        %div= @store ?  "地址： #{@store.address}" : ""
    .submit-session
      =link_to '上一步', checkout_path, class: 'btn btn-previous', onClick: analytic_event("checkout_step_2", "click", "previous_step")
      =submit_tag '下一步', class: 'btn', onClick: analytic_event("checkout_step_3", "enter", "無")

app/views/carts/success.html.haml
.success
  .text-align
    恭喜您！已成功完成購物！
  .image
  - if current_user
    .text-align
      親愛的
      %span.name= current_user.user_name
      ，非常感謝您在萌萌屋消費！
      %br/
      您可以在「我的訂單」掌握商品的最新動向。
      %br/
      商品抵達您指定超商時，會有簡訊通知，
      %br/
      還請您多加留意！萌萌屋全體期待您再次光臨！！
  -else
    .text-align
      親愛的訂購人，非常感謝您在萌萌屋消費！
      %br/
      此次的購物明細已寄至您的信箱，商品抵達您指定超商時，
      %br/
      會有簡訊通知，還請您多加留意！
      %br/
      萌萌屋全體期待您再次光臨！！

  .submit-session
    =link_to '繼續購物', root_path , class: 'btn', onClick: analytic_event("checkout_step_4", "click", "finish_purchase")